### ISSUE TITLE
Licensing Choice

### ISSUE THREAD

**Issue by micahkwok** [UBC-MDS/eda_utils_py#54]
Setting up this issue for discussion of if we should change our licensing in our Python and R issue. Feel free to leave your thoughts and discuss.

**Comment by micahkwok** [comment]
Having taken a look at the lecture 8 material, I would agree with Frank, who said on the call yesterday, in sticking with the MIT license. 

Since our package seems more for our own purposes of software development and workflows conceptual understanding MIT seems to fit what we require according to https://choosealicense.com. People can do what they want with it, but we have limitation of liability.   

If we go this route, I think we will need to add everyone's names into the License though.

**Comment by fatse** [comment]
Agreed with your comment above @micahkwok.

I, too, think that the MIT license is more in line with our intentions and the purpose of this package. 
So, I propose to not change the license and continue using the MIT license and just update it with our names and the year in the dedicated place in the license file.

**Comment by micahkwok** [comment]
For documentation purposes: 

It was agreed to by all members of the group that we will simply stick with the MIT license in our weekly meeting. The purposes are already listed above in this thread.

I have added the names to our license in the latest PR request for both Python and R packages.
